package edu.ucaldas.back.models.review;

import java.time.LocalDateTime;

import edu.ucaldas.back.models.user.User;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Inheritance;
import jakarta.persistence.InheritanceType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents an abstract review entity in the system.
 * This class is annotated with JPA annotations to map it to a database table named "review".
 * It uses the JOINED inheritance strategy for handling inheritance in JPA.
 * 
 * <p>Fields:</p>
 * <ul>
 *   <li><b>id:</b> The unique identifier for the review, auto-generated by the database.</li>
 *   <li><b>writer:</b> The user who wrote the review, represented as a many-to-one relationship.</li>
 *   <li><b>comment:</b> The textual content of the review.</li>
 *   <li><b>dateTime:</b> The date and time when the review was created.</li>
 *   <li><b>stars:</b> The rating given in the review, represented as an integer.</li>
 *   <li><b>isActive:</b> A boolean flag indicating whether the review is active or not.</li>
 * </ul>
 * 
 * <p>Constructors:</p>
 * <ul>
 *   <li>A no-argument constructor for JPA and framework usage.</li>
 *   <li>A parameterized constructor for creating a review with a writer, comment, and stars.
 *       This constructor initializes the dateTime to the current time and sets isActive to true.</li>
 * </ul>
 * 
 * <p>Annotations:</p>
 * <ul>
 *   <li><b>@Entity:</b> Marks this class as a JPA entity.</li>
 *   <li><b>@Table:</b> Specifies the table name in the database.</li>
 *   <li><b>@Inheritance:</b> Defines the inheritance strategy for JPA.</li>
 *   <li><b>@Getter, @Setter:</b> Lombok annotations to generate getter and setter methods.</li>
 *   <li><b>@NoArgsConstructor, @AllArgsConstructor:</b> Lombok annotations to generate constructors.</li>
 *   <li><b>@EqualsAndHashCode:</b> Lombok annotation to generate equals and hashCode methods based on the "id" field.</li>
 * </ul>
 */
@Entity
@Table(name = "review")
@Inheritance(strategy = InheritanceType.JOINED)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "id")
public abstract class Review {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    @ManyToOne
    @JoinColumn(name = "user_reviewer_id")
    private User writer;
    private String comment;
    private LocalDateTime dateTime;
    private int stars;
    private boolean isActive;

    public Review(User writer, String comment, int stars) {
        this.writer = writer;
        this.comment = comment;
        this.stars = stars;
        this.dateTime = LocalDateTime.now();
        this.isActive = true;
    }

}
